// @generated by Index-ComponentCodegen
// hash: 867fc2e8829888a233161e2627e8723be86e4e1676853c796bca31c95448ff8e
//
// DO NOT EDIT — this file is regenerated whenever the editor's
// 'Rebuild Engine' flow runs (or when Index-ComponentCodegen is
// invoked manually). Manual edits are lost on the next regeneration.
//
// This TU compiles into Index-GameComponents.dll (the sidecar). The
// engine loads the DLL at scene-manager init and resolves the
// exported 'IndexRegisterCodegenComponents' symbol — no static link.

#include "pch.hpp"
#include "Scene/ComponentRegistrationHelpers.hpp"
#include "Scene/SceneManager.hpp"

#if defined(_WIN32)
    #define INDEX_GAMECOMPONENTS_EXPORT extern "C" __declspec(dllexport)
#else
    #define INDEX_GAMECOMPONENTS_EXPORT extern "C" __attribute__((visibility("default")))
#endif

INDEX_GAMECOMPONENTS_EXPORT void IndexRegisterCodegenComponents(Index::SceneManager* sceneManager) {
    if (!sceneManager) return;
    // No user-defined C# components carry [NativeComponent(..., Generate = true)].
}
