using System.Text;

namespace Index.ComponentCodegen;

internal static class CppEmitter
{
    // Placeholder Program.cs replaces with the SHA-256 of the emitted body.
    // Putting the hash on line 2 (right under @generated) lets FileMatchesHash
    // do a one-line read for the idempotency check.
    public const string HashPlaceholder = "<HASH_TO_BE_FILLED>";

    // Exported C entry point the engine resolves with GetProcAddress/dlsym.
    // Lives in the sidecar DLL (Index-GameComponents.dll); the engine has
    // no static link dependency on this symbol — when the sidecar is
    // missing the engine simply skips the call.
    private const string ExportedSymbolName = "IndexRegisterCodegenComponents";

    public static string Emit(List<DiscoveredComponent> components, string generatedNamespace)
    {
        var sb = new StringBuilder(16 * 1024);

        sb.AppendLine("// @generated by Index-ComponentCodegen");
        sb.AppendLine($"// hash: {HashPlaceholder}");
        sb.AppendLine("//");
        sb.AppendLine("// DO NOT EDIT — this file is regenerated whenever the editor's");
        sb.AppendLine("// 'Rebuild Engine' flow runs (or when Index-ComponentCodegen is");
        sb.AppendLine("// invoked manually). Manual edits are lost on the next regeneration.");
        sb.AppendLine("//");
        sb.AppendLine("// This TU compiles into Index-GameComponents.dll (the sidecar). The");
        sb.AppendLine("// engine loads the DLL at scene-manager init and resolves the");
        sb.AppendLine($"// exported '{ExportedSymbolName}' symbol — no static link.");
        sb.AppendLine();
        sb.AppendLine("#include \"pch.hpp\"");
        sb.AppendLine("#include \"Scene/ComponentRegistrationHelpers.hpp\"");
        sb.AppendLine("#include \"Scene/SceneManager.hpp\"");

        // Conditional includes — only pull glm if any component uses a vector.
        var usesVec = components.Any(c =>
            c.Fields.Any(f =>
                f.CppType.StartsWith("glm::", StringComparison.Ordinal)));
        if (usesVec)
        {
            sb.AppendLine("#include <glm/glm.hpp>");
        }

        var usesColor = components.Any(c =>
            c.Fields.Any(f => f.CppType == "Color"));
        if (usesColor)
        {
            sb.AppendLine("#include \"Collections/Color.hpp\"");
        }

        // PropertyDescriptor list construction requires the inspector helpers.
        var anyInspectorFields = components.Any(c =>
            c.Fields.Any(f => !f.HideFromInspector));
        if (anyInspectorFields)
        {
            sb.AppendLine("#include \"Inspector/PropertyRegistration.hpp\"");
        }

        sb.AppendLine();

        // Component struct definitions — only emitted when at least one
        // component carries [NativeComponent(..., Generate = true)]. The
        // exported registration function is always emitted regardless, so
        // the engine's GetProcAddress lookup succeeds even on empty inputs.
        if (components.Count > 0)
        {
            EmitNamespace(sb, generatedNamespace, () =>
            {
                foreach (var comp in components)
                {
                    EmitStruct(sb, comp);
                    sb.AppendLine();
                }
            });
            sb.AppendLine();
        }

        EmitExport(sb, components, generatedNamespace);

        return sb.ToString();
    }

    private static void EmitExport(StringBuilder sb, List<DiscoveredComponent> components, string generatedNamespace)
    {
        // Cross-platform DLL export macro. The sidecar build defines
        // IDX_BUILD_GAMECOMPONENTS so the macro becomes __declspec(dllexport)
        // / __attribute__((visibility("default"))) inside this TU; the
        // engine consumer side doesn't see this header so no IMPORT side
        // exists.
        sb.AppendLine("#if defined(_WIN32)");
        sb.AppendLine("    #define INDEX_GAMECOMPONENTS_EXPORT extern \"C\" __declspec(dllexport)");
        sb.AppendLine("#else");
        sb.AppendLine("    #define INDEX_GAMECOMPONENTS_EXPORT extern \"C\" __attribute__((visibility(\"default\")))");
        sb.AppendLine("#endif");
        sb.AppendLine();

        sb.AppendLine($"INDEX_GAMECOMPONENTS_EXPORT void {ExportedSymbolName}(Index::SceneManager* sceneManager) {{");
        sb.AppendLine("    if (!sceneManager) return;");

        if (components.Count == 0)
        {
            sb.AppendLine("    // No user-defined C# components carry [NativeComponent(..., Generate = true)].");
            sb.AppendLine("}");
            return;
        }

        sb.AppendLine("    using Index::Codegen::RegisterComponent;");
        foreach (var comp in components)
        {
            sb.AppendLine($"    using {generatedNamespace}::{comp.CSharpTypeName};");
        }
        sb.AppendLine();

        foreach (var comp in components)
        {
            EmitRegistration(sb, comp);
            sb.AppendLine();
        }

        sb.AppendLine("}");
    }

    private static void EmitNamespace(StringBuilder sb, string ns, Action body)
    {
        // Split "Index::Generated" into nested namespaces so the compiler
        // emits the same symbol mangling as if it were nested.
        var parts = ns.Split("::", StringSplitOptions.RemoveEmptyEntries);
        for (int i = 0; i < parts.Length; ++i)
        {
            sb.AppendLine($"{Indent(i)}namespace {parts[i]} {{");
        }
        sb.AppendLine();
        body();
        for (int i = parts.Length - 1; i >= 0; --i)
        {
            sb.AppendLine($"{Indent(i)}}}");
        }
    }

    private static void EmitStruct(StringBuilder sb, DiscoveredComponent comp)
    {
        var indent = Indent(2);
        sb.AppendLine($"{indent}struct {comp.CSharpTypeName} {{");
        foreach (var f in comp.Fields)
        {
            var def = f.CppDefaultExpr is null ? ";" : $" = {f.CppDefaultExpr};";
            sb.AppendLine($"{indent}    {f.CppType} {f.CSharpName}{def}");
        }
        sb.AppendLine($"{indent}}};");
        sb.AppendLine($"{indent}static_assert(sizeof({comp.CSharpTypeName}) == {comp.ManagedSize}, " +
                      $"\"Layout drift between C++ {comp.CSharpTypeName} and C# mirror — \" " +
                      $"\"field order, padding, or types diverged.\");");
    }

    private static void EmitRegistration(StringBuilder sb, DiscoveredComponent comp)
    {
        var indent = "    ";
        var inspectorFields = comp.Fields.Where(f => !f.HideFromInspector).ToList();

        var categoryEnum = comp.Category == "Tag"
            ? "ComponentCategory::Tag"
            : "ComponentCategory::Component";

        // Empty-property registration uses the compact form — no property
        // list, the engine just stores the metadata.
        if (inspectorFields.Count == 0)
        {
            sb.AppendLine($"{indent}RegisterComponent<{comp.CSharpTypeName}>(*sceneManager, {Quoted(comp.NativeName)},");
            sb.AppendLine($"{indent}    {categoryEnum}, {Quoted(comp.Subcategory)}, {Quoted(comp.NativeName)});");
            return;
        }

        sb.AppendLine($"{indent}RegisterComponent<{comp.CSharpTypeName}>(*sceneManager, {Quoted(comp.NativeName)},");
        sb.AppendLine($"{indent}    {categoryEnum}, {Quoted(comp.Subcategory)}, {Quoted(comp.NativeName)},");
        sb.AppendLine($"{indent}    {{");

        for (int i = 0; i < inspectorFields.Count; ++i)
        {
            var f = inspectorFields[i];
            var trailing = (i == inspectorFields.Count - 1) ? "" : ",";

            // Properties::Make signature is (name, display, &T::field, PropertyMetadata = {}).
            // Chain Clamp / Tooltip / etc. onto a single PropertyMetadata{} so both
            // apply to the same field — separate metadata args don't compose.
            string metaArg = "";
            if (f.Meta is { } m)
            {
                var chain = new System.Text.StringBuilder();
                if (m.RangeMin.HasValue && m.RangeMax.HasValue)
                {
                    chain.Append($".WithClamp(static_cast<double>({m.RangeMin.Value.ToString("R", System.Globalization.CultureInfo.InvariantCulture)}), ");
                    chain.Append($"static_cast<double>({m.RangeMax.Value.ToString("R", System.Globalization.CultureInfo.InvariantCulture)}))");
                }
                if (!string.IsNullOrEmpty(m.Tooltip))
                {
                    chain.Append($".WithTooltip({Quoted(m.Tooltip)})");
                }
                if (chain.Length > 0) metaArg = $", PropertyMetadata{{}}{chain}";
            }

            sb.Append($"{indent}        Properties::Make({Quoted(f.CSharpName)}, {Quoted(f.DisplayName)}, ");
            sb.Append($"&{comp.CSharpTypeName}::{f.CSharpName}{metaArg})");
            sb.AppendLine(trailing);
        }

        sb.AppendLine($"{indent}    }});");
    }

    private static string Quoted(string s) => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private static string Indent(int level) => new(' ', level * 4);
}
